name: Generic

counters:
  - id: counter-a
    name: Counter A
    initialValue: 0
    persistsBetweenTurns: true
    alwaysDisplayed: true

  - id: counter-b
    name: Counter B
    initialValue: 0
    persistsBetweenTurns: true
    alwaysDisplayed: false

  - id: counter-c
    name: Counter C
    initialValue: 0
    persistsBetweenTurns: true
    alwaysDisplayed: false

players:
  defaultPlayerCount: 2
  overrides: []
