name: Generic

counterNames:
  authority: Counter A
  money: Counter B
  attack: Counter C

counterResetsOnTurn:
  authority: false
  money: false
  attack: false

counterVisibleForNonActive:
  authority: true
  money: false
  attack: false

defaultCounterValues:
  authority: 0
  money: 0
  attack: 0

players:
  - Player 1
  - Player 2
