name: Magic-Like

counters:
  - id: life
    name: Life
    initialValue: 20
    persistsBetweenTurns: true
    alwaysDisplayed: true

  - id: mana
    name: Mana
    initialValue: 0
    persistsBetweenTurns: false
    alwaysDisplayed: false

  - id: damage
    name: Damage
    initialValue: 0
    persistsBetweenTurns: false
    alwaysDisplayed: true

players:
  defaultPlayerCount: 2
  overrides: []
