name: Star Realms

counters:
  - id: authority
    name: Authority
    icon: authority
    initialValue: 50
    persistsBetweenTurns: true
    alwaysDisplayed: true

  - id: trade
    name: Trade
    icon: trade
    initialValue: 0
    persistsBetweenTurns: false
    alwaysDisplayed: false

  - id: combat
    name: Combat
    icon: combat
    initialValue: 0
    persistsBetweenTurns: false
    alwaysDisplayed: true

players:
  defaultPlayerCount: 2
  overrides: []
