name: Star Realms

counters:
  - id: authority
    name: Authority
    icon: authority
    initialValue: 50
    persistsBetweenTurns: yes
    alwaysDisplayed: yes

  - id: trade
    name: Trade
    icon: trade
    initialValue: 0
    persistsBetweenTurns: no
    alwaysDisplayed: no

  - id: combat
    name: Combat
    icon: combat
    initialValue: 0
    persistsBetweenTurns: no
    alwaysDisplayed: no

players:
  defaultPlayerCount: 2
  overrides: []
